TRUNCATE TABLE peers CASCADE;
TRUNCATE TABLE tasks CASCADE;
TRUNCATE TABLE checks RESTART IDENTITY CASCADE;
TRUNCATE TABLE p2p RESTART IDENTITY CASCADE;
TRUNCATE TABLE verter RESTART IDENTITY CASCADE;
TRUNCATE TABLE xp RESTART IDENTITY CASCADE;
TRUNCATE TABLE transferred_points RESTART IDENTITY CASCADE;
TRUNCATE TABLE friends RESTART IDENTITY CASCADE;
TRUNCATE TABLE recommendations RESTART IDENTITY CASCADE;
TRUNCATE TABLE time_tracking RESTART IDENTITY CASCADE;

DELETE FROM databasechangelog WHERE filename LIKE '%/v-2.0-insert/%';


--- Checking ---
SELECT * FROM databasechangelog;
